name: Docker Image Export

on:
  push:
  workflow_dispatch:

jobs:
  export-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 确保你可以访问整个 Git 历史记录以进行提交

    - name: Pull Docker Image
      run: docker pull ubuntu:20.04

    - name: Save Docker Image
      run: docker save -o oracle-xe-11g.tar oracle-xe-11g:latest

    - name: Add and Commit oracle-xe-11g.tar
      run: |
        git config --local user.email "yuanzhiyi98@gmail.com"
        git config --local user.name "zhiyi98"
        git add oracle-xe-11g.tar
        git commit -m "Actions add a new tar file"
        
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: main
